@startuml
!include ./eventstorming/single.puml

Person('admin', '管理员')

Command('CreateApp')[
    创建应用
    ---
    应用编码不能重复
    应用名称不能重复
]

Command('UpdateApp')[
    修改应用
    ---
    应用编码不能重复
    应用名称不能重复
]

Command('DeleteApp')[
    删除应用
    ---
]

Command('CreateUser')[
    新建用户
    ---
]

Command('UpdateUser')[
    修改用户
    ---
]

Command('EnableUser')[
    启用用户
    ---
]

Command('DisableUser')[
    禁用用户
    ---
]

Command('CreateMenu')[
    创建菜单
    ---
]

Command('UpdateMenu')[
    更新菜单
    ---
]
Command('DeleteMenu')[
    删除菜单
    ---
]


Command('CreateApi')[
    创建Api
    ---
]

Command('UpdateApi')[
    更新Api
    ---
]

Command('DeleteApi')[
    删除Api
    ---
]

Command('CreateApiCategory')[
    创建Api分类
    ---
]

Command('UpdateApiCategory')[
    更新Api分类
    ---
]

Command('DeleteApiCategory')[
    删除Api分类
    ---
]

Aggregate('App')[
    应用
    ---
    code 应用编码
    ---
    应用名称
]

DomainEvent('AppCreated')[
    应用已创建
]

DomainEvent('AppChanged')[
    应用已被修改
]

DomainEvent('UserCreated')[
    用户已创建
]

DomainEvent('UserChanged')[
    用户已被修改
]

DomainEvent('UserDisabled')[
    用户已启用
]

DomainEvent('UserEnabled')[
    用户已禁用
]

DomainEvent('UserDeleted')[
    用户已删除
]

DomainEvent('UserJoinedGroup')[
    用户已加入用户组
]

DomainEvent('UserLeftGroup')[
    用户已离开用户组
]

DomainEvent('UserGroupCreated')[
    用户组已创建
]

DomainEvent('UserGroupDeleted')[
    用户组已删除
]

DomainEvent('RoleCreated')[
    角色已创建
]

DomainEvent('RoleDeleted')[
    角色已删除
]

DomainEvent('RolePermissionChanged')[
    角色权限发生变更
]

DomainEvent('MenuCreated')[
    菜单已创建
]

DomainEvent('MenuChanged')[
    菜单已修改
]

DomainEvent('MenuDeleted')[
    菜单已删除
]

DomainEvent('APICreated')[
    接口已创建
]

DomainEvent('APIChanged')[
    接口已修改
]

DomainEvent('APIDeleted')[
    接口已删除
]

DomainEvent('APICategoryCreated')[
    接口分类已创建
]

DomainEvent('APICategoryDeleted')[
    接口分类已删除
]


DomainEvent('PermissionResourceCreated')[
    权限资源已创建
]

DomainEvent('PermissionResourceDeleted')[
    权限资源已删除
]

' 应用

admin --> CreateApp
admin --> UpdateApp
admin --> DeleteApp

CreateApp --> App
UpdateApp --> App

App --> AppCreated
App --> AppChanged

' 用户

admin --> CreateUser
admin --> UpdateUser
admin --> EnableUser
admin --> DisableUser

CreateUser --> UserCreated
UpdateUser --> UserChanged
EnableUser --> UserEnabled
DisableUser --> UserDisabled

admin --> APICategoryCreated
admin --> APICategoryDeleted

admin --> CreateMenu
admin --> UpdateMenu
admin --> DeleteMenu
admin --> CreateApi
admin --> UpdateApi
admin --> DeleteApi
admin --> CreateApiCategory
admin --> UpdateApiCategory
admin --> DeleteApiCategory

CreateMenu --> MenuCreated
UpdateMenu --> MenuChanged
DeleteMenu --> MenuDeleted
CreateApi --> APICreated
UpdateApi --> APIChanged
DeleteApi --> APIDeleted


' person --> CreateApp

' person --> UpdateApp

' CreateApp --> Application

' UpdateApp --> Application

' Application --> AppCreated



'System('system')
'Command('command1', 'command')
'Aggregate('aggregate')
'DomainEvent('domain_event', 'domain event')
'ReadModel('read_model', 'read model')
'UserInterface('user_interface', 'user interface')
'Command('command2', 'command')
'Policy('policy')
'Person('person')
'
'command1 --> aggregate : invoked on
'command1 --> system : invoked on
'aggregate --> domain_event : generates
'system --> domain_event : generates
'domain_event --> read_model : translated into
'read_model --> user_interface : displayed by
'domain_event --> policy : triggers
'policy --> command2 : invokes
'person --> command2 : invokes
'person -l-> user_interface : used by

@enduml