@startuml Iam
!include ./eventstorming/single.puml

Person('admin', '管理员')

Command('CreatePermission')[
    新建权限资源
    ---
]

Command('DeletePermission')[
    删除权限资源
    ---
]

DomainEvent('UserJoinedGroup')[
    用户已加入用户组
]

DomainEvent('UserLeftGroup')[
    用户已离开用户组
]

DomainEvent('RoleCreated')[
    角色已创建
]

DomainEvent('RoleDeleted')[
    角色已删除
]

DomainEvent('RolePermissionChanged')[
    角色权限发生变更
]

DomainEvent('PermissionResourceCreated')[
    权限资源已创建
]

DomainEvent('PermissionResourceDeleted')[
    权限资源已删除
]

Aggregate('Permission')[
    资源权限
    ---
    权限资源类型
    资源id
]

' 应用

Command('CreateApp')[
    创建应用
    ---
    应用编码不能重复
    应用名称不能重复
]

Command('UpdateApp')[
    修改应用
    ---
    应用编码不能重复
    应用名称不能重复
]

Command('DeleteApp')[
    删除应用
    ---
]

DomainEvent('AppCreated')[
    应用已创建
]

DomainEvent('AppChanged')[
    应用已被修改
]

Aggregate('App')[
    应用
    ---
    code 应用编码
    ---
    应用名称
]

admin --> CreateApp
admin --> UpdateApp
admin --> DeleteApp

CreateApp --> App
UpdateApp --> App
DeleteApp --> App

App --> AppCreated
App --> AppChanged

' 用户

Command('UpdateUser')[
    修改用户
    ---
]

Command('CreateUser')[
    新建用户
    --rules--
    用户名/手机号/邮箱要保证唯一
]

Command('EnableUser')[
    启用用户
    ---
]

Command('DisableUser')[
    禁用用户
    ---
]

DomainEvent('UserCreated')[
    用户已创建
]

DomainEvent('UserChanged')[
    用户已被修改
]

DomainEvent('UserDisabled')[
    用户已启用
]

DomainEvent('UserEnabled')[
    用户已禁用
]

DomainEvent('UserDeleted')[
    用户已删除
]

Aggregate('User')[
    用户
    ---
    用户名
    手机号
    邮箱
    密码
]

admin --> CreateUser
admin --> UpdateUser
admin --> EnableUser
admin --> DisableUser

CreateUser --> User
UpdateUser --> User
EnableUser --> User
DisableUser --> User

User --> UserCreated
User --> UserChanged
User --> UserEnabled
User --> UserDisabled


' 用户组

Command('CreateUserGroup')[
    创建用户组
    ---
]

Command('UpdateUserGroup')[
    更新用户组
    ---
]

DomainEvent('UserGroupCreated')[
    用户组已创建
]

DomainEvent('UserGroupDeleted')[
    用户组已删除
]

Aggregate('UserGroup')[
    用户组
    ---
    名称
    上级用户组
    类型
]

admin --> CreateUserGroup
admin --> UpdateUserGroup
CreateUserGroup --> UserGroup
UpdateUserGroup --> UserGroup
UserGroup --> UserGroupCreated


' Api分类

Command('CreateApiCategory')[
    创建Api分类
    ---
]

Command('UpdateApiCategory')[
    更新Api分类
    ---
]

Command('DeleteApiCategory')[
    删除Api分类
    ---
]

DomainEvent('APICategoryCreated')[
    接口分类已创建
]

DomainEvent('APICategoryDeleted')[
    接口分类已删除
]

Aggregate('ApiCategory')[
    Api分类
    --fields--
    应用id
    名称
]

admin --> CreateApiCategory
admin --> UpdateApiCategory
admin --> DeleteApiCategory

CreateApiCategory --> ApiCategory
UpdateApiCategory --> ApiCategory
DeleteApiCategory --> ApiCategory

ApiCategory --> APICategoryCreated
ApiCategory --> APICategoryDeleted

' Api


Command('CreateApi')[
    创建Api
    ---
]

Command('UpdateApi')[
    更新Api
    ---
]

Command('DeleteApi')[
    删除Api
    ---
]

DomainEvent('APICreated')[
    接口已创建
]

DomainEvent('APIChanged')[
    接口已修改
]

DomainEvent('APIDeleted')[
    接口已删除
]

Aggregate('Api')[
    Api
    --fields--
    Api名称
    应用id
    分类id
    Uri
    HttpMethod
    认证授权类型
    是否包含路径参数
    状态
]


admin --> CreateApi
admin --> UpdateApi
admin --> DeleteApi

CreateApi --> Api
UpdateApi --> Api
DeleteApi --> Api

Api --> APICreated
Api --> APIChanged
Api --> APIDeleted

APICreated --> CreatePermission
APIDeleted --> DeletePermission

' 菜单

Command('CreateMenu')[
    创建菜单
    ---
]

Command('UpdateMenu')[
    更新菜单
    ---
    状态更新时把下级菜单状态也一并更新
]

Command('DeleteMenu')[
    删除菜单
    ---
]

Aggregate('Menu')[
    菜单
    ---
    菜单名称
    菜单编码
    组件
    Icon

]

DomainEvent('MenuCreated')[
    菜单已创建
]

DomainEvent('MenuChanged')[
    菜单已修改
]

DomainEvent('MenuDeleted')[
    菜单已删除
]

admin --> CreateMenu
admin --> UpdateMenu
admin --> DeleteMenu

CreateMenu --> Menu
UpdateMenu --> Menu
DeleteMenu --> Menu

Menu --> MenuCreated
Menu --> MenuChanged
Menu --> MenuDeleted

MenuCreated --> CreatePermission
MenuDeleted --> DeletePermission

CreatePermission --> Permission
DeletePermission --> Permission


' person --> CreateApp

' person --> UpdateApp

' CreateApp --> Application

' UpdateApp --> Application

' Application --> AppCreated



'System('system')
'Command('command1', 'command')
'Aggregate('aggregate')
'DomainEvent('domain_event', 'domain event')
'ReadModel('read_model', 'read model')
'UserInterface('user_interface', 'user interface')
'Command('command2', 'command')
'Policy('policy')
'Person('person')
'
'command1 --> aggregate : invoked on
'command1 --> system : invoked on
'aggregate --> domain_event : generates
'system --> domain_event : generates
'domain_event --> read_model : translated into
'read_model --> user_interface : displayed by
'domain_event --> policy : triggers
'policy --> command2 : invokes
'person --> command2 : invokes
'person -l-> user_interface : used by

@enduml